# General settings
set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins"
setw -g mouse on
set-option -g default-shell /opt/homebrew/bin/zsh

# True color settings
set -g default-terminal 'screen-256color'
set -sa terminal-features ',xterm-256color:RGB'
set -s escape-time 0
set -g base-index 1
# set-option -g allow-passthrough on

# Key bindings
# Set the prefix to ^A
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# vi key movement for copy/pasta mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Add to your tmux.conf file
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

set -g @catppuccin_flavor 'mocha'
run "$TMUX_PLUGIN_MANAGER_PATH/tmux/catppuccin.tmux"

# List of plugins
set -g @plugin 'tmux-plugins/tpm' # Tmux Plugin Manager
set -g @plugin 'catppuccin/tmux#v2.1.2' # See https://github.com/catppuccin/tmux/tags for additional tags
# ...alongside
set -g @plugin 'tmux-plugins/tmux-sensible' # Tmux Sensible defaults
set -g @plugin 'tmux-plugins/tmux-resurrect' # Restore tmux environment after system restart
set -g @plugin 'tmux-plugins/tmux-continuum' # continuous saving of tmux environment, auto start and restore (relies on the save state of resurrect)
set -g @plugin 'christoomey/vim-tmux-navigator' # Navigate seamlessly between vim and tmux splits using a consistent set of hotkeys
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# General statusline customisation
# set -g status-style 'bg=terminal'
set -g status-style "bg=#{@thm_mantle}"
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[0]' ''
set -g status 2

# status left style
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_mantle},bold]  #S },#{#[bg=#{@thm_mantle},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_mantle},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# set -g status-justify "left"

# status right style
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#{?#{e|>=:10,#{battery_percentage}},#{#[bg=#{@thm_red},fg=#{@thm_mantle}]},#{#[bg=#{@thm_mantle},fg=#{@thm_pink}]}} #{battery_icon} #{battery_percentage} "
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@thm_mantle}]#{?#{==:#{online_status},ok},#[fg=#{@thm_mauve}] 󰖩 on ,#[fg=#{@thm_red},bold]#[reverse] 󰖪 off }"
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# window style
set -wg automatic-rename on
set -g automatic-rename-format ''
set -g window-status-separator '|'
set -g status-justify 'absolute-centre'
set -g @catppuccin_window_status_style 'custom'
set -g @catppuccin_window_flags ""
set -g @catppuccin_window_number ""
set -g @catppuccin_window_text "#[fg=#{@thm_rosewater},bg=#{@thm_mantle}] #I#{?#{!=:#{window_name},},: #W ,}"
set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_current_text "#[fg=#{@thm_mantle},bg=#{@thm_peach}] #I#{?#{!=:#{window_name},},: #W ,}"

# Configure Online
set -g @online_icon "ok"
set -g @offline_icon "nok"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$TMUX_PLUGIN_MANAGER_PATH/tpm/tpm"
